//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Edward
//

import Foundation



class ___VARIABLE_productName:identifier___PresenterImp<T: ___VARIABLE_productName:identifier___View>: MVPPresenter {

    weak var view: T?

    required init(view: T) {
        self.view = view
    }
}
extension ___VARIABLE_productName:identifier___PresenterImp: ___VARIABLE_productName:identifier___Presenter {

}
