//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Edward
//

import Foundation

// MARK: View -
protocol ___VARIABLE_productName:identifier___View: MVPView {

}

// MARK: Presenter -
protocol ___VARIABLE_productName:identifier___Presenter {
    
}
